spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sheets
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  data:
    mongodb:
      uri: mongodb://mongo:mongopass@localhost:27017/sheets?authSource=admin
      database: sheets
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      database: 0
  redis:
    host: localhost
    port: 6379
    password: redispass
    timeout: 5000
    connect-timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 4
        max-wait: 2000ms
        time-between-eviction-runs: 30000
      shutdown-timeout: 3000ms
# Logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      jooq: INFO
    io.lettuce: DEBUG
