openapi: 3.0.3
components:
  schemas:
    CellRequest:
      type: object
      required:
        - row
        - column
        - data
      properties:
        row:
          type: integer
          description: Row index of the cell
          example: 1
        column:
          type: integer
          description: Column index of the cell
          example: 1
        data:
          type: string
          description: Cell content (primitive value or expression)
          example: "=SUM(A1,B1)"

    CellResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the cell (format sheetId:row:column)
          example: "1:1:1"
        sheetId:
          type: integer
          format: int64
          description: ID of the sheet containing the cell
          example: 1
        row:
          type: integer
          description: Row index of the cell
          example: 1
        column:
          type: integer
          description: Column index of the cell
          example: 1
        data:
          type: string
          description: Raw cell content (primitive value or expression)
          example: "=SUM(A1,B1)"
        dataType:
          type: string
          enum: [PRIMITIVE, EXPRESSION]
          description: Type of data in the cell
          example: "EXPRESSION"
        evaluatedValue:
          type: string
          description: Evaluated value of the cell
          example: "10"
        createdAt:
          type: string
          format: date-time
          description: Time when the cell was created
          example: "2025-05-24T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Time when the cell was last updated
          example: "2025-05-24T12:00:00Z"

    CellBatchRequest:
      type: object
      required:
        - cells
      properties:
        cells:
          type: array
          items:
            type: object
            required:
              - row
              - column
              - data
            properties:
              row:
                type: integer
                description: Row index of the cell
                example: 1
              column:
                type: integer
                description: Column index of the cell
                example: 1
              data:
                type: string
                description: Cell content (primitive value or expression)
                example: "=SUM(A1,B1)"

    CellBatchResponse:
      type: object
      properties:
        cells:
          type: array
          items:
            $ref: '#/components/schemas/CellResponse'

    CellErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        error:
          type: string
          description: Error type
          example: "Bad Request"
        message:
          type: string
          description: Error message
          example: "Invalid cell reference"
        path:
          type: string
          description: Request path
          example: "/api/v1/sheet/1/cell"
        timestamp:
          type: string
          format: date-time
          description: Time when the error occurred
          example: "2025-05-24T12:00:00Z"
        details:
          type: object
          description: Additional error details
          additionalProperties: true
